# Generated by Django 3.2.3 on 2021-07-05 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последняя дата обновления')),
                ('first_name', models.CharField(db_index=True, max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=128, verbose_name='Фамилия')),
                ('middle_name', models.CharField(db_index=True, default='', max_length=128, verbose_name='Отчество')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Женский'), (1, 'Мужской')], verbose_name='Пол')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('id_doc_type', models.CharField(blank=True, default='', max_length=32, verbose_name='Документ подтверждающий личность')),
                ('id_doc_series', models.CharField(blank=True, default='', max_length=32, verbose_name='Серия документа')),
                ('id_doc_num', models.CharField(blank=True, default='', max_length=32, verbose_name='Номер документа')),
                ('insurance_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Номер страхового полиса')),
                ('insurance_company_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Реестровый номер страховой компании')),
                ('self_phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Контактный номер телефона')),
                ('work_phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Рабочий номер телефона')),
                ('reg_address', models.CharField(blank=True, default='', max_length=512, verbose_name='Адрес регистрации')),
                ('fact_address', models.CharField(blank=True, default='', max_length=512, verbose_name='Адрес фактический')),
                ('work_address', models.CharField(blank=True, default='', max_length=512, verbose_name='Адрес работы/учебы')),
                ('work_place', models.CharField(blank=True, default='', max_length=512, verbose_name='Место работы/учебы')),
                ('work_post', models.CharField(blank=True, default='', max_length=128, verbose_name='Должность')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
    ]
