# Generated by Django 3.2.3 on 2021-08-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='work_phone',
        ),
    ]
