# Generated by Django 3.2.3 on 2021-08-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'Только просмотр записей'), (2, 'Просмотр, создание и редактирование записей'), (3, 'Просмотр, создание редактирование и удаление записей'), (10, 'Администратор')], default=1, verbose_name='Права пользователя'),
        ),
    ]
