# Generated by Django 3.2.3 on 2021-07-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
