# Generated by Django 3.2.3 on 2021-08-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0002_research_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='reason',
            field=models.SmallIntegerField(choices=[(1, 'Беременность'), (2, 'Госпитализация'), (3, 'Контакт'), (4, 'Медицинский работник'), (5, 'Новорожденный'), (6, 'Острый бронхит'), (7, 'Обследование'), (8, 'Пневмония'), (9, 'Прибывшие'), (10, 'COVID-19'), (11, 'Хронический фарингит'), (12, 'Другое'), (13, 'ОРВИ')], db_index=True, verbose_name='Цель исследования'),
        ),
    ]
