# Generated by Django 3.2.3 on 2021-08-03 12:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0003_alter_research_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ([django.db.models.expressions.OrderBy(django.db.models.expressions.F('total_num'), descending=True, nulls_last=False)],)},
        ),
        migrations.AddConstraint(
            model_name='research',
            constraint=models.UniqueConstraint(fields=('daily_num', 'created_at'), name='daily_num_and_date'),
        ),
    ]
