# Generated by Django 3.2.3 on 2021-08-03 13:10

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0004_auto_20210803_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('total_num'), descending=True, nulls_last=False)]},
        ),
    ]
