# Generated by Django 3.2.3 on 2021-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0006_auto_20210803_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='collect_date',
            field=models.DateField(db_index=True, verbose_name='Дата поступления'),
        ),
    ]
