version: "3.7"

networks:
    resources:
        external: true

services:
    django:
        image: iriskin/laboratory-reestr-back:latest
        volumes:
            - ./static:/opt/app/static
        env_file:
            - .env
        networks:
            - resources
        labels:
            - "traefik.enable=true"

            - "traefik.http.routers.laboratory-django.rule=Host(`laboratory.kvd-rostov.ru`) && Path(`/admin`)) || Host(`laboratory.kvd-rostov.ru`) && Path(`/api`))"
            - "traefik.http.routers.laboratory-django.entrypoints=https"
            - "traefik.http.routers.laboratory-django.tls=true"
            - "traefik.http.routers.laboratory-django.tls.certresolver=le"
        restart: always

    django-static:
        image: nginx:latest
        depends_on:
            - django
        volumes:
            - ./compose/nginx/conf.d:/etc/nginx/conf.d
            - ./static:/www/static
            - ./media:/www/media
        ports:
            - "80"
        environment:
            - NGINX_PORT=80
        networks:
            - resources
        labels:
            - "traefik.enable=true"

            - "traefik.http.routers.laboratory-nginx.rule=Host(`laboratory.kvd-rostov.ru`) && Path(`/django-static`)) || Host(`laboratory.kvd-rostov.ru`) && Path(`/media`))"
            django-static
            - "traefik.http.routers.laboratory-nginx.entrypoints=https"
            - "traefik.http.routers.laboratory-nginx.tls=true"
            - "traefik.http.routers.laboratory-nginx.tls.certresolver=le"
        restart: always
